# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GIS.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_GIS(object):
    def setupUi(self, MainWindow_GIS):
        MainWindow_GIS.setObjectName("MainWindow_GIS")
        MainWindow_GIS.resize(1900, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow_GIS)
        self.centralwidget.setObjectName("centralwidget")
        self.label_imgplan_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_imgplan_2.setGeometry(QtCore.QRect(790, 450, 54, 16))
        self.label_imgplan_2.setObjectName("label_imgplan_2")
        self.label_sensor02 = QtWidgets.QLabel(self.centralwidget)
        self.label_sensor02.setGeometry(QtCore.QRect(148, 1, 101, 16))
        self.label_sensor02.setStyleSheet("color: rgb(255, 79, 48);")
        self.label_sensor02.setObjectName("label_sensor02")
        self.label_imgplanlong_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_imgplanlong_2.setGeometry(QtCore.QRect(1050, 380, 54, 16))
        self.label_imgplanlong_2.setObjectName("label_imgplanlong_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1050, 360, 71, 16))
        self.label_7.setObjectName("label_7")
        self.label_imgshow02 = QtWidgets.QLabel(self.centralwidget)
        self.label_imgshow02.setGeometry(QtCore.QRect(370, 660, 54, 20))
        self.label_imgshow02.setObjectName("label_imgshow02")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(780, 100, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 770, 111, 51))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1260, 450, 171, 16))
        self.label_8.setObjectName("label_8")
        self.label_sensor03 = QtWidgets.QLabel(self.centralwidget)
        self.label_sensor03.setGeometry(QtCore.QRect(295, 1, 91, 16))
        self.label_sensor03.setStyleSheet("color: rgb(255, 79, 48);")
        self.label_sensor03.setObjectName("label_sensor03")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(1110, 580, 71, 16))
        self.label_9.setObjectName("label_9")
        self.label_sensor04 = QtWidgets.QLabel(self.centralwidget)
        self.label_sensor04.setGeometry(QtCore.QRect(442, 1, 91, 16))
        self.label_sensor04.setStyleSheet("color: rgb(255, 79, 48);")
        self.label_sensor04.setObjectName("label_sensor04")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 450, 161, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 660, 111, 51))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(530, 540, 111, 51))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_imgzhanqu = QtWidgets.QLabel(self.centralwidget)
        self.label_imgzhanqu.setGeometry(QtCore.QRect(713, 120, 51, 181))
        self.label_imgzhanqu.setText("")
        self.label_imgzhanqu.setScaledContents(True)
        self.label_imgzhanqu.setObjectName("label_imgzhanqu")
        self.label_sensor05 = QtWidgets.QLabel(self.centralwidget)
        self.label_sensor05.setGeometry(QtCore.QRect(589, 1, 141, 16))
        self.label_sensor05.setStyleSheet("color: rgb(255, 79, 48);")
        self.label_sensor05.setObjectName("label_sensor05")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 750, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1390, 680, 71, 16))
        self.label_10.setObjectName("label_10")
        self.label_imgboard = QtWidgets.QLabel(self.centralwidget)
        self.label_imgboard.setGeometry(QtCore.QRect(290, 660, 54, 16))
        self.label_imgboard.setObjectName("label_imgboard")
        self.label_imgplan = QtWidgets.QLabel(self.centralwidget)
        self.label_imgplan.setGeometry(QtCore.QRect(130, 770, 54, 16))
        self.label_imgplan.setObjectName("label_imgplan")
        self.label_imggroup_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_imggroup_2.setGeometry(QtCore.QRect(1390, 700, 54, 16))
        self.label_imggroup_2.setObjectName("label_imggroup_2")
        self.label_imgshow03 = QtWidgets.QLabel(self.centralwidget)
        self.label_imgshow03.setGeometry(QtCore.QRect(530, 540, 54, 20))
        self.label_imgshow03.setObjectName("label_imgshow03")
        self.label_imgplanlong = QtWidgets.QLabel(self.centralwidget)
        self.label_imgplanlong.setGeometry(QtCore.QRect(210, 480, 54, 16))
        self.label_imgplanlong.setObjectName("label_imgplanlong")
        self.label_imggroup = QtWidgets.QLabel(self.centralwidget)
        self.label_imggroup.setGeometry(QtCore.QRect(460, 540, 54, 16))
        self.label_imggroup.setObjectName("label_imggroup")
        self.label_imgshow01 = QtWidgets.QLabel(self.centralwidget)
        self.label_imgshow01.setGeometry(QtCore.QRect(230, 770, 54, 20))
        self.label_imgshow01.setObjectName("label_imgshow01")
        self.label_imgboard_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_imgboard_2.setGeometry(QtCore.QRect(1260, 470, 54, 16))
        self.label_imgboard_2.setObjectName("label_imgboard_2")
        self.label_imgplan_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_imgplan_3.setGeometry(QtCore.QRect(1110, 600, 54, 16))
        self.label_imgplan_3.setObjectName("label_imgplan_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 640, 131, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 510, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_sensor01 = QtWidgets.QLabel(self.centralwidget)
        self.label_sensor01.setGeometry(QtCore.QRect(1, 1, 101, 16))
        self.label_sensor01.setStyleSheet("color: rgb(255, 79, 48);")
        self.label_sensor01.setObjectName("label_sensor01")
        self.label_imgzhanqu_img = QtWidgets.QLabel(self.centralwidget)
        self.label_imgzhanqu_img.setGeometry(QtCore.QRect(780, 120, 241, 171))
        self.label_imgzhanqu_img.setAutoFillBackground(False)
        self.label_imgzhanqu_img.setText("")
        self.label_imgzhanqu_img.setScaledContents(True)
        self.label_imgzhanqu_img.setObjectName("label_imgzhanqu_img")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(790, 430, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_imgshow01.raise_()
        self.label_imgshow03.raise_()
        self.label_imgplan_2.raise_()
        self.label_sensor02.raise_()
        self.label_imgplanlong_2.raise_()
        self.label_7.raise_()
        self.label_imgshow02.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.label_8.raise_()
        self.label_sensor03.raise_()
        self.label_9.raise_()
        self.label_sensor04.raise_()
        self.label_2.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.label_imgzhanqu.raise_()
        self.label_sensor05.raise_()
        self.label_3.raise_()
        self.label_10.raise_()
        self.label_imgboard.raise_()
        self.label_imgplan.raise_()
        self.label_imggroup_2.raise_()
        self.label_imgplanlong.raise_()
        self.label_imggroup.raise_()
        self.label_imgboard_2.raise_()
        self.label_imgplan_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_sensor01.raise_()
        self.label_imgzhanqu_img.raise_()
        self.label_6.raise_()
        MainWindow_GIS.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_GIS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1900, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow_GIS.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_GIS)
        self.statusbar.setObjectName("statusbar")
        MainWindow_GIS.setStatusBar(self.statusbar)
        self.actionenablevideo = QtWidgets.QAction(MainWindow_GIS)
        self.actionenablevideo.setCheckable(True)
        self.actionenablevideo.setObjectName("actionenablevideo")
        self.actionenablehand = QtWidgets.QAction(MainWindow_GIS)
        self.actionenablehand.setCheckable(True)
        self.actionenablehand.setObjectName("actionenablehand")
        self.actionenableVideo = QtWidgets.QAction(MainWindow_GIS)
        self.actionenableVideo.setCheckable(True)
        self.actionenableVideo.setObjectName("actionenableVideo")
        self.actionenableHand = QtWidgets.QAction(MainWindow_GIS)
        self.actionenableHand.setCheckable(True)
        self.actionenableHand.setObjectName("actionenableHand")
        self.actionsetup = QtWidgets.QAction(MainWindow_GIS)
        self.actionsetup.setObjectName("actionsetup")
        self.actionenableSensor = QtWidgets.QAction(MainWindow_GIS)
        self.actionenableSensor.setCheckable(True)
        self.actionenableSensor.setObjectName("actionenableSensor")
        self.menu.addAction(self.actionenableVideo)
        self.menu.addAction(self.actionenableHand)
        self.menu.addAction(self.actionenableSensor)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow_GIS)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_GIS)

    def retranslateUi(self, MainWindow_GIS):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_GIS.setWindowTitle(_translate("MainWindow_GIS", "自动WQ控制系统"))
        self.label_imgplan_2.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_sensor02.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_imgplanlong_2.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_7.setText(_translate("MainWindow_GIS", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">无人机</span></p></body></html>"))
        self.label_imgshow02.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label.setText(_translate("MainWindow_GIS", "<html><head/><body><p><span style=\" color:#00ff00;\">协同与控制一体化指挥厅</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow_GIS", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">巡逻机器车</span></p></body></html>"))
        self.label_sensor03.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_9.setText(_translate("MainWindow_GIS", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">无人机</span></p></body></html>"))
        self.label_sensor04.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_2.setText(_translate("MainWindow_GIS", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">无人机</span></p></body></html>"))
        self.label_sensor05.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_3.setText(_translate("MainWindow_GIS", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">无人机</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow_GIS", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">巡逻分队</span></p></body></html>"))
        self.label_imgboard.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_imgplan.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_imggroup_2.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_imgshow03.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_imgplanlong.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_imggroup.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_imgshow01.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_imgboard_2.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_imgplan_3.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_4.setText(_translate("MainWindow_GIS", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">巡逻机器车</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow_GIS", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">巡逻分队</span></p></body></html>"))
        self.label_sensor01.setText(_translate("MainWindow_GIS", "TextLabel"))
        self.label_6.setText(_translate("MainWindow_GIS", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">无人机</span></p></body></html>"))
        self.menu.setTitle(_translate("MainWindow_GIS", "设置"))
        self.actionenablevideo.setText(_translate("MainWindow_GIS", "使能视频"))
        self.actionenablehand.setText(_translate("MainWindow_GIS", "使能摇杆"))
        self.actionenableVideo.setText(_translate("MainWindow_GIS", "使能视频"))
        self.actionenableHand.setText(_translate("MainWindow_GIS", "使能摇杆"))
        self.actionsetup.setText(_translate("MainWindow_GIS", "配置"))
        self.actionenableSensor.setText(_translate("MainWindow_GIS", "使能传感器"))

