# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1248, 804)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_img = QtWidgets.QLabel(self.centralwidget)
        self.label_img.setObjectName("label_img")
        self.horizontalLayout.addWidget(self.label_img)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_video = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_video.setObjectName("checkBox_video")
        self.verticalLayout.addWidget(self.checkBox_video)
        self.checkBox_plat = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_plat.setObjectName("checkBox_plat")
        self.verticalLayout.addWidget(self.checkBox_plat)
        self.checkBox_auto = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_auto.setObjectName("checkBox_auto")
        self.verticalLayout.addWidget(self.checkBox_auto)
        self.checkBox_recongnise = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_recongnise.setObjectName("checkBox_recongnise")
        self.verticalLayout.addWidget(self.checkBox_recongnise)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 201, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.pushButton_lift = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_lift.setText("")
        self.pushButton_lift.setObjectName("pushButton_lift")
        self.gridLayout_2.addWidget(self.pushButton_lift, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 2, 1, 1)
        self.pushButton_down = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_down.setText("")
        self.pushButton_down.setObjectName("pushButton_down")
        self.gridLayout_2.addWidget(self.pushButton_down, 3, 1, 1, 1)
        self.pushButton_up = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_up.setText("")
        self.pushButton_up.setObjectName("pushButton_up")
        self.gridLayout_2.addWidget(self.pushButton_up, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 2, 1, 1)
        self.pushButton_right = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_right.setText("")
        self.pushButton_right.setObjectName("pushButton_right")
        self.gridLayout_2.addWidget(self.pushButton_right, 2, 2, 1, 1)
        self.pushButton_scan = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_scan.setObjectName("pushButton_scan")
        self.gridLayout_2.addWidget(self.pushButton_scan, 2, 1, 1, 1)
        self.pushButton_zoom01 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_zoom01.setGeometry(QtCore.QRect(30, 160, 75, 23))
        self.pushButton_zoom01.setObjectName("pushButton_zoom01")
        self.pushButton_zoom02 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_zoom02.setGeometry(QtCore.QRect(130, 160, 75, 23))
        self.pushButton_zoom02.setObjectName("pushButton_zoom02")
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.checkBox_sensor = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_sensor.setGeometry(QtCore.QRect(30, 20, 121, 16))
        self.checkBox_sensor.setObjectName("checkBox_sensor")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(31, 40, 211, 111))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_sensor01 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_sensor01.setObjectName("label_sensor01")
        self.verticalLayout_2.addWidget(self.label_sensor01)
        self.label_sensor02 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_sensor02.setObjectName("label_sensor02")
        self.verticalLayout_2.addWidget(self.label_sensor02)
        self.label_sensor03 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_sensor03.setObjectName("label_sensor03")
        self.verticalLayout_2.addWidget(self.label_sensor03)
        self.label_sensor04 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_sensor04.setObjectName("label_sensor04")
        self.verticalLayout_2.addWidget(self.label_sensor04)
        self.label_sensor05 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_sensor05.setObjectName("label_sensor05")
        self.verticalLayout_2.addWidget(self.label_sensor05)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 20, 131, 121))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_shut01 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_shut01.setText("")
        self.pushButton_shut01.setObjectName("pushButton_shut01")
        self.gridLayout.addWidget(self.pushButton_shut01, 0, 0, 1, 1)
        self.pushButton_shut02 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_shut02.setText("")
        self.pushButton_shut02.setObjectName("pushButton_shut02")
        self.gridLayout.addWidget(self.pushButton_shut02, 0, 1, 1, 1)
        self.pushButton_shut03 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_shut03.setText("")
        self.pushButton_shut03.setObjectName("pushButton_shut03")
        self.gridLayout.addWidget(self.pushButton_shut03, 1, 0, 1, 1)
        self.pushButton_shut04 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_shut04.setText("")
        self.pushButton_shut04.setObjectName("pushButton_shut04")
        self.gridLayout.addWidget(self.pushButton_shut04, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1248, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionstep = QtWidgets.QAction(MainWindow)
        self.actionstep.setObjectName("actionstep")
        self.action_setup = QtWidgets.QAction(MainWindow)
        self.action_setup.setObjectName("action_setup")
        self.actionGIS = QtWidgets.QAction(MainWindow)
        self.actionGIS.setObjectName("actionGIS")
        self.actionGIS_2 = QtWidgets.QAction(MainWindow)
        self.actionGIS_2.setObjectName("actionGIS_2")
        self.actionV0_2 = QtWidgets.QAction(MainWindow)
        self.actionV0_2.setObjectName("actionV0_2")
        self.menu.addAction(self.actionGIS_2)
        self.menu.addAction(self.action_setup)
        self.menu_2.addAction(self.actionV0_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "东土自动WQ系统"))
        self.label_img.setText(_translate("MainWindow", "test"))
        self.checkBox_video.setText(_translate("MainWindow", "使能视频"))
        self.checkBox_plat.setText(_translate("MainWindow", "云台2使能"))
        self.checkBox_auto.setText(_translate("MainWindow", "云台2自动使能"))
        self.checkBox_recongnise.setText(_translate("MainWindow", "自动识别控制使能"))
        self.groupBox_3.setTitle(_translate("MainWindow", "云台远控"))
        self.pushButton_scan.setText(_translate("MainWindow", "扫射"))
        self.pushButton_zoom01.setText(_translate("MainWindow", "ZoomIn"))
        self.pushButton_zoom02.setText(_translate("MainWindow", "Zoomout"))
        self.groupBox.setTitle(_translate("MainWindow", "遥信"))
        self.checkBox_sensor.setText(_translate("MainWindow", "使能遥信"))
        self.label_sensor01.setText(_translate("MainWindow", "传感器01：value"))
        self.label_sensor02.setText(_translate("MainWindow", "传感器01：value"))
        self.label_sensor03.setText(_translate("MainWindow", "传感器01：value"))
        self.label_sensor04.setText(_translate("MainWindow", "传感器01：value"))
        self.label_sensor05.setText(_translate("MainWindow", "传感器01：value"))
        self.groupBox_2.setTitle(_translate("MainWindow", "遥控"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "about"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionstep.setText(_translate("MainWindow", "步进值"))
        self.action_setup.setText(_translate("MainWindow", "设置"))
        self.actionGIS.setText(_translate("MainWindow", "GIS地图"))
        self.actionGIS_2.setText(_translate("MainWindow", "GIS"))
        self.actionV0_2.setText(_translate("MainWindow", "Version_0.2"))

